apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend-v2
spec:
  template:
    spec:
      containers:
      - image: frontend-v2-image
        ports:
        - containerPort: 8080
