apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: sofie-cluster
  namespace: sofie
  # You can add any necessary annotations here if you have specific ones for your GitOps flow
  # annotations:
  #   your-gitops-tool/sync-options: Prune=true
spec:
  backup:
    enabled: true
    image: percona/percona-backup-mongodb:2.9.1
    pitr:
      compressionLevel: 6
      compressionType: gzip
      enabled: false
      oplogOnly: false
  crVersion: 1.20.0
  image: percona/percona-server-mongodb:7.0.18-11
  imagePullPolicy: Always
  pmm:
    enabled: false
    image: percona/pmm-client:2.44.1
    serverHost: monitoring-service
  replsets:
  - affinity:
      antiAffinityTopologyKey: kubernetes.io/hostname
    arbiter:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      enabled: false
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 1
    expose:
      enabled: false
      type: ClusterIP
    name: rs0
    nonvoting:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      enabled: false
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 3
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    podDisruptionBudget:
      maxUnavailable: 1
    resources:
      limits:
        cpu: 300m
        memory: 0.5G
      requests:
        cpu: 300m
        memory: 0.5G
    size: 3
    volumeSpec:
      persistentVolumeClaim:
        resources:
          requests:
            storage: 3Gi
  secrets:
    encryptionKey: sofie-cluster-mongodb-encryption-key
    users: sofie-cluster-secrets
  users: # Add this section if it's missing or to define your Sofie user
  - name: sofie-mongo-admin # The username Sofie will use
    # Password will be auto-generated by the operator and stored in 'sofie-cluster-secrets'
    # The key in the secret will likely be MONGODB_SOFIE_MONGO_ADMIN_PASSWORD
    # (or similar, check Percona docs for exact key naming convention based on username)
    roles:
    - name: userAdminAnyDatabase
      db: admin
    - name: readWriteAnyDatabase # Grant broad permissions for the meteor database
      db: meteor # Or specify 'meteor' if Sofie only needs access to its own DB
  sharding:
    configsvrReplSet:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        enabled: false
        type: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 3
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 3Gi
    enabled: true
    mongos:
      affinity:
        antiAffinityTopologyKey: kubernetes.io/hostname
      expose:
        type: ClusterIP
      podDisruptionBudget:
        maxUnavailable: 1
      resources:
        limits:
          cpu: 300m
          memory: 0.5G
        requests:
          cpu: 300m
          memory: 0.5G
      size: 3
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: disabled
    schedule: 0 2 * * *
    setFCV: false
    versionServiceEndpoint: https://check.percona.com
