# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: sofie-core-config
  namespace: sofie
data:
  # Replace <user>, <password> with base64 decoded values or reference the secret directly if possible
  # Ensure replicaSet=rs0 matches the name in the StatefulSet command
  MONGO_URL: "mongodb://databaseAdmin:qfXy6GyPtUm8QphQpU@sofie-cluster-mongos.sofie.svc.cluster.local:27017/meteor"
  # Replace with the final external HTTPS URL
  ROOT_URL: "https://sofie.yourdomain.com"
  PORT: "3000"
