
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "reverse_proxy"
version = "0.1.0"
packages = [{include = "reverse_proxy", from = "src"}]

[tool.pytest.ini_options]
pythonpath = [
  "src",
  "tests"
]
