steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '.'
    dir: 'orchestrator/agent'

  # 2. Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA'
    dir: 'orchestrator/agent'

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--min-instances=1'
      - '--cpu=2'
      - '--memory=2Gi'
      - '--session-affinity'
      - '--service-account=websocket-service-account@$PROJECT_ID.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_GENAI_USE_VERTEXAI=${_GOOGLE_GENAI_USE_VERTEXAI},GOOGLE_API_KEY=${_GOOGLE_API_KEY},CUEZ_AGENT_URL=${_CUEZ_AGENT_URL},POSTURE_STUBZY_AGENT_URL=${_POSTURE_STUBZY_AGENT_URL},POSTURE_AGENT_URL=${_POSTURE_AGENT_URL}'
    dir: 'orchestrator/agent'

# Define images to be pushed to Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE_NAME}:$COMMIT_SHA'

# Define substitutions
substitutions:
  _SERVICE_NAME: 'orchestrator-agent'
  _REGION: 'us-central1'
  _REPOSITORY: 'cloud-run-source-deploy' # Default repo name for Cloud Run builds
  _GOOGLE_GENAI_USE_VERTEXAI: 'FALSE'
  _GOOGLE_API_KEY: ''
  _CUEZ_AGENT_URL: 'http://localhost:8001'
  _POSTURE_STUBZY_AGENT_URL: 'http://localhost:10001'
  _POSTURE_AGENT_URL: 'http://localhost:10002'

# Cloud Build options
options:
  logging: CLOUD_LOGGING_ONLY
