apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/invoker-iam-disabled: 'true'
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/sessionAffinity: "true"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: orchestrator-agent
        ports:
        - containerPort: 8080
        timeoutSeconds: 3600
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
