apiVersion: skaffold/v4beta7
kind: Config
build:
  artifacts:
  - image: orchestrator-agent
    docker:
      dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - base
deploy:
  cloudrun:
    serviceAccount: ${RUN_SERVICE_ACCOUNT_EMAIL}
profiles:
  - name: stable
    manifests:
      kustomize:
        paths:
          - overlays/stable
  - name: staging
    manifests:
      kustomize:
        paths:
          - overlays/staging
