apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend-v2
spec:
  template:
    spec:
      containers:
      - name: app
        image: frontend-v2-image
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
