apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend-v2-staging
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/invoker-iam-disabled: 'true'
spec:
  template:
    spec:
      containers:
      - image: frontend-v2-image
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        env:
          - name: APP_ENV
            value: "staging"
