apiVersion: skaffold/v4beta1
kind: Config
manifests:
  rawYaml:
  - service.yaml
deploy:
  cloudrun: {}
build:
  artifacts:
  - image: frontend-v2-image
    docker:
      dockerfile: Dockerfile
profiles:
  - name: stable
    deploy:
      cloudrun:
        env:
        - name: APP_ENV
          value: "stable"
  - name: staging
    deploy:
      cloudrun:
        env:
        - name: APP_ENV
          value: "staging"